"""
search table

Revision ID: 801688bc1087
Revises: c8c97129733d
Create Date: 2022-03-17 14:19:30.526039

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '801688bc1087'
down_revision = 'c8c97129733d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('include_concepts', sa.JSON(), nullable=True),
    sa.Column('exclude_concepts', sa.JSON(), nullable=True),
    sa.Column('include_relations', sa.JSON(), nullable=True),
    sa.Column('exclude_relations', sa.JSON(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user-searches')
    # ### end Alembic commands ###
