"""
tutorial column

Revision ID: 998028418369
Revises: f4dcb65c6813
Create Date: 2022-04-01 17:41:47.506704

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '998028418369'
down_revision = 'f4dcb65c6813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brainworks-users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutorial', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brainworks-users', schema=None) as batch_op:
        batch_op.drop_column('tutorial')

    # ### end Alembic commands ###
