"""
new search query fields

Revision ID: afbc1b34446c
Revises: d6e6b5892d08
Create Date: 2022-04-20 11:28:16.446537

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'afbc1b34446c'
down_revision = 'd6e6b5892d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user-searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('representation', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('authors', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('journals', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('grants', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user-searches', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('grants')
        batch_op.drop_column('journals')
        batch_op.drop_column('authors')
        batch_op.drop_column('representation')

    # ### end Alembic commands ###
