"""
login attempt table

Revision ID: bca0b6e75aef
Revises: dbd50dff7941
Create Date: 2022-08-04 17:15:03.954486

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'bca0b6e75aef'
down_revision = 'dbd50dff7941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login-attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('browser', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login-attempts')
    # ### end Alembic commands ###
