"""
verification_and_admin

Revision ID: c8c97129733d
Revises: 7bb3c4a9cc92
Create Date: 2022-03-17 09:52:46.689814

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8c97129733d'
down_revision = '7bb3c4a9cc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification-tokens',
    sa.Column('token', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('brainworks-users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brainworks-users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('created')
        batch_op.drop_column('admin')

    op.create_table('new_table',
    sa.Column('key', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('JSON', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('verification-tokens')
    # ### end Alembic commands ###
