"""
user archive

Revision ID: d6e6b5892d08
Revises: 998028418369
Create Date: 2022-04-07 13:56:21.240495

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd6e6b5892d08'
down_revision = '998028418369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('country', sqlalchemy_utils.types.country.CountryType(length=2), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user-archive')
    # ### end Alembic commands ###
