"""
user log table

Revision ID: dbd50dff7941
Revises: afbc1b34446c
Create Date: 2022-07-26 13:07:53.900677

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbd50dff7941'
down_revision = 'afbc1b34446c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('who_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=100), nullable=True),
    sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('country', sqlalchemy_utils.types.country.CountryType(length=2), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('tutorial', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('user-archive', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user-archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))

    op.drop_table('user-log')
    # ### end Alembic commands ###
