"""
Search date index

Revision ID: f4dcb65c6813
Revises: 801688bc1087
Create Date: 2022-03-24 17:21:02.209620

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f4dcb65c6813'
down_revision = '801688bc1087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user-searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user-searches_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user-searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user-searches_date'))

    # ### end Alembic commands ###
